export const almostBlack = '#525252'
export const specialRed = '#DB3F74'
export const textDarkGrey = '#1F2228'
export const textGrey = '#757575'
export const textLightGrey = '#9B9B9B'
export const bgLightGrey = '#f1f1f1'

export const bgLightPink = '#FEEEF4'
export const specialPink = '#DB3F74'
export const muteBlue = '#ECEEF1'
